---
- name: launch ec2 instance
  ec2: 
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    instance_type: "{{ INSTANCE }}"
    key_name: "{{ KEY_NAME }}"
    image: "{{ BASE_AMI }}"
    user_data: "{{ lookup('file', '/home/ansible/ansible/playbooks/ans_env.sh')}}"
    ec2_region: "{{ AWS_REGION }}"
    assign_public_ip: yes
    group: "{{ GRP_NAME }}"
    vpc_subnet_id: "{{ default_vpc_subnet }}"
    wait: yes   
    count_tag: 
      application: Gym-management_system
    exact_count: 1
  register: ec2
  
- name: Add newly added instance to inventory
  local_action: lineinfile
                path=/etc/ansible/hosts
                regexp={{ item.public_ip }}
                insertafter="[local]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"
  
- name: wait for SSH to come up 
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: "{{ ec2.instances }}"

- name: Add tag to instances
  local_action: ec2_tag resource={{ item.id }} region={{ AWS_REGION }} state=present
  with_items: "{{ ec2.instances }}"
  args: 
    tags: 
      Name: gym-system-cloud
      
- name: make known host entry
  shell: "ssh-keyscan {{ item.public_ip }} >> /home/ansible/.ssh/known_hosts" 
  with_items: "{{ ec2.instances }}"
   
