---
# tasks file for gym-system-cloud
- name: Provison EC2 instance
  include: ec2_provision.yml  
  delegate_to: localhost
  
- name: Install Docker 
  include: docker_install_centos.yml
  delegate_to: "{{ ec2.instances.public_ip }}" 

- name: Launch containers
  include: docker_containers_launch.yml
  delegate_to: "{{ ec2.instances.public_ip }}"

